JDBC_DRIVER=org.postgresql.Driver
USER=postgres
#DB_URL=jdbc:postgresql://localhost:5432/sales
#PASS=root
DB_URL=jdbc:postgresql://db.talentify.in/sales_demo
PASS=cx6ac54nmgGtLD1y
SIGNAL_ANALYZER_URL=http://localhost/appie/wordsimilarity
THRESHOLD_VALUE=0.85
THRESHOLD_VALUE_WATSON=0.1
WAIT_TIME=20000