package edu.uniba.di.lacam.kdde.ws4j.servlet;
public enum MatchTypes 
{ 
    EXACT_MATCH, CONTAINS, SYNONYM_EXACT, SYNONYM_CONTAINS, SENTENCE_SIMILARITY, SENTENCE_SIMILARITY_SYNONYM,DATA_MUSE, NO_MATCH, COORDINATE_TERM_CONTAINS, COORDINATE_TERM_EXACT, HYPONYM_CONTAINS, HYPONYM_EXACT, HYPERNYM_CONTAINS, HYPERNYM_EXACT, SYNONYM_SENTENCE_EXACT, SYNONYM_SENTENCE_CONTAINS, STANFORD_SIMILARITY
} 